name: check-tests-statuses
on:
  - pull_request
  -
jobs:
  upgrade_requirements:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: ["3.8"]

    steps:

      - name: setup tubular
        run: |
          git clone https://github.com/openedx/tubular.git
          cd tubular
          pip install -r requirements/base.txt
          
      - name: run command
        run: |
          cd tubular
          check_pr_tests_status.py --org openedx --repo credentials 1893
